/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scard;

import java.math.BigInteger;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Signature;
import java.security.interfaces.RSAPublicKey;
import java.security.spec.RSAPublicKeySpec;
import java.util.Arrays;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Naptien extends javax.swing.JFrame {
    private theBus thebus;
    String otp;
    BigInteger modulusPubkey,exponentPubkey ;
     
    public Naptien() {
        this.thebus = BusForm.thebus;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_sotien = new javax.swing.JTextField();
        btn_NapTien = new javax.swing.JButton();
        txt_pin = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txt_OTP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_checkOTP = new javax.swing.JTextField();
        btn_otp = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel2.setText("Nhập số tiền:");

        jLabel3.setText("Nhập mã PIN:");

        btn_NapTien.setBackground(new java.awt.Color(204, 204, 204));
        btn_NapTien.setText("Nạp");
        btn_NapTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NapTienActionPerformed(evt);
            }
        });

        txt_pin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pinActionPerformed(evt);
            }
        });

        jLabel4.setText("VND");

        txt_OTP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N

        jLabel6.setText("Nhập OTP:");

        btn_otp.setBackground(new java.awt.Color(204, 204, 204));
        btn_otp.setText("Lấy OTP");
        btn_otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_otpActionPerformed(evt);
            }
        });

        jLabel5.setText("000");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nạp tiền");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 11, 94, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel6)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_sotien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(txt_checkOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_NapTien, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_otp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_sotien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txt_pin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_otp)
                    .addComponent(txt_OTP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6))
                    .addComponent(txt_checkOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_NapTien)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NapTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NapTienActionPerformed
        String pin = Arrays.toString(txt_pin.getPassword());
        String checkotp = txt_checkOTP.getText();
        System.out.print(checkotp);
        if(checkotp.equals(otp) != true){
            JOptionPane.showMessageDialog(this, "OTP không đúng.");
        }else{
            byte[] cmdcreateSig = {(byte) 0xA0, (byte) 0x16, (byte) 0x01, (byte) 0x00};
            String sotien = txt_sotien.getText();
            String st = Integer.toHexString(Integer.valueOf(sotien));
            short verifylen=0;
            if(Integer.valueOf(sotien)<= 255){
                verifylen = 7;
            }else if(Integer.valueOf(sotien)<= 4095){
                verifylen = 9;
            }else{
                verifylen = 10;
            }
            System.out.println(st);
            String arraysend= checkotp.concat(pin);
            thebus.sendAPDUtoApplet(cmdcreateSig,arraysend.getBytes());
            byte[] aa = thebus.resAPDU.getData();
            if(aa.length ==1|| thebus.resAPDU.getSW1()!= 0x90){
                JOptionPane.showMessageDialog(this, "Giao dịch không thành công. Mã PIN không đúng");
                txt_OTP.setText("OTP hết hạn.");
                txt_checkOTP.setText("");
            }else{
                byte[] input  = arraysend.getBytes();
                String resCheck = String.format("%x", new BigInteger(1, aa));
                boolean verifyCheck = true;
              
                try {
                    verifyCheck = Verify_Signature(input,resCheck.getBytes());
                } catch (Exception ex) {
                    Logger.getLogger(thanhtoan.class.getName()).log(Level.SEVERE, null, ex);
                }
                if(verifyCheck)
                {
                byte[] cmdverify = {(byte) 0xA0, (byte) 0x16, (byte) 0x02, (byte) 0x00};
                byte[] verify = new byte[7];
                if(verifylen == 7){
                    byte[] b = checkotp.getBytes();
                    System.arraycopy(b, (short)0, verify, (short)0, b.length);
                    verify[6]= Byte.valueOf(st,16);
                }
                if(verifylen == 9){
                    verify = new byte[verifylen];
                    byte[] b = checkotp.getBytes();
                    System.arraycopy(b, (short)0, verify, (short)0, b.length);
                    String[] tach = st.split("",3);
                    verify[6] = Byte.valueOf(tach[0],16);
                    verify[7] = Byte.valueOf(tach[1],16);
                    verify[8] = Byte.valueOf(tach[2],16);
                }
                if(verifylen == 10){
                    verify = new byte[verifylen];
                    byte[] b = checkotp.getBytes();
                    System.arraycopy(b, (short)0, verify, (short)0, b.length);
                    String[] tach = st.split("",4);
                    verify[6] = Byte.valueOf(tach[0],16);
                    verify[7] = Byte.valueOf(tach[1],16);
                    verify[8] = Byte.valueOf(tach[2],16);
                    verify[9] = Byte.valueOf(tach[3],16);
                }
                thebus.sendAPDUtoApplet(cmdverify, verify);
                byte[] res = thebus.resAPDU.getData();
                if(res[0] == 0x00){
                    JOptionPane.showMessageDialog(this, "Giao dịch không thành công. Xác thực lỗi");
                    txt_OTP.setText("OTP hết hạn.");
                    txt_checkOTP.setText("");
                }else if (res[0] == 0x01){
                    JOptionPane.showMessageDialog(this, "Giao dịch thành công.");
                    setVisible(false);
                }else if(res[0] == 0x02){
                    JOptionPane.showMessageDialog(this, "Giao dịch không thành công. Số tiền giao dịch vượt tối đa");
                    txt_OTP.setText("OTP hết hạn.");
                    txt_checkOTP.setText("");
                }
                }else
                {
                     JOptionPane.showMessageDialog(this, "Giao dịch không thành công. Xác thực lỗi");
                    txt_OTP.setText("OTP hết hạn.");
                    txt_checkOTP.setText("");
                }
            }
        }
    }//GEN-LAST:event_btn_NapTienActionPerformed
 public boolean Verify_Signature(byte[] input,byte[] signatureToVerify) throws Exception{
         byte[] getModulusPubkey = {(byte) 0xA0, (byte) 0x22, (byte) 0x01, (byte) 0x01};
          thebus.sendAPDUtoApplet(getModulusPubkey);
          BigInteger resModulusPubkey = new BigInteger(1, thebus.resAPDU.getData());
          byte[] getExponentPubkey = {(byte) 0xA0, (byte) 0x22, (byte) 0x02, (byte) 0x01};
          thebus.sendAPDUtoApplet(getExponentPubkey);
          BigInteger resExponentPubkey = new BigInteger(1, thebus.resAPDU.getData());
          
        modulusPubkey = resModulusPubkey;
        exponentPubkey = resExponentPubkey;
        System.out.println("pubkey: "+modulusPubkey + " / "+exponentPubkey );
       
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        RSAPublicKeySpec pubKeySpec = new RSAPublicKeySpec(modulusPubkey, exponentPubkey);
        PublicKey key = (RSAPublicKey) keyFactory.generatePublic(pubKeySpec);
        
        Signature signature = Signature.getInstance("MD5WithRSA");
        signature.initVerify(key);
        signature.update(input);
        return signature.verify(signatureToVerify);
    }
    private void txt_pinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_pinActionPerformed

    private void btn_otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_otpActionPerformed
//        byte[] cmdOTP = {(byte) 0xA0, (byte) 0x16, (byte) 0x00, (byte) 0x00};
//        thebus.sendAPDUtoApplet(cmdOTP);
//        byte[] a = thebus.resAPDU.getData();
         char[] a = generateOTP(6);
        otp = "";
        for (int i = 0; i < a.length; i++) {
            otp += a[i];
        }
        txt_OTP.setText(otp);
    }//GEN-LAST:event_btn_otpActionPerformed
    private static char[] generateOTP(int length) {
      String numbers = "158AB90HJNO234Uab67cdCDefghjKLouMklmEFGnywYW";
      Random random = new Random();
      char[] otp = new char[length];

      for(int i = 0; i< length ; i++) {
         otp[i] = numbers.charAt(random.nextInt(numbers.length()));
      }
      return otp;
   }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_NapTien;
    private javax.swing.JButton btn_otp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txt_OTP;
    private javax.swing.JTextField txt_checkOTP;
    private javax.swing.JPasswordField txt_pin;
    private javax.swing.JTextField txt_sotien;
    // End of variables declaration//GEN-END:variables
}
